### ISSUE TITLE
Elasticsearch

### ISSUE THREAD

**Issue by 32graham** [jspm/registry#401]
I am trying to use the [Elasticsearch JavaScript API](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/quick-start.html).

I have done:

    jspm install npm:elasticsearch

Then when I try:

    import elasticsearch from "elasticsearch";

I get:
![capture](https://cloud.githubusercontent.com/assets/821554/7941849/9b8e71e6-091f-11e5-902f-cac5c5eb90e6.PNG)

But when I import the same module in node it works. Am I doing something wrong?

**Comment by guybedford** [comment]
Thanks for posting - the issue is due to the browser mapping in https://github.com/elastic/elasticsearch-js/blob/master/package.json#L16.

This can be removed with an override like:

override.json
```json
{
  "browser": {
    "./src/lib/connectors/index.js": "./src/lib/connectors/browser_index.js",
    "./src/lib/loggers/index.js": "./src/lib/loggers/browser_index.js",
    "./src/lib/apis/index.js": "./src/lib/apis/browser_index.js",
    "./test/mocks/server.js": "./test/mocks/browser_server.js",
    "lodash": "lodash-compat"
  }
}
```

installing via `jspm install npm:elasticsearch -o override.json`.

Let me know if that works ok for you, and we can add this to the registry for others.

**Comment by 32graham** [comment]
Thanks, I installed via `jspm install npm:elasticsearch -o override.json` with the `override.json` file as you said. Now I get a different error. Any ideas?

![capture](https://cloud.githubusercontent.com/assets/821554/7944458/54b059c2-0930-11e5-86c9-226ae4c0aed7.PNG)

**Comment by guybedford** [comment]
That one is a bug. Thanks I've fixed it in https://github.com/jspm/npm/commit/4aa9f8f9991189b8be2aa2e7e366109cc9808b0c, it will come in the next release soon, or you're welcome to install `jspm-npm` from GitHub on master.

**Comment by 32graham** [comment]
I am unsure how to install the latest from GitHub. If you can point me in the right direction I will test it for you, otherwise I can wait until the next release.

Here is what I have been trying, and it does not seem to help

     npm install http://github.com/jspm/npm/tarball/master -g

**Comment by guybedford** [comment]
`npm install jspm/npm#master` should work here I think?

**Comment by 32graham** [comment]
I have tried both `npm install jspm/npm#master` and `npm install -g jspm/npm#master` and then I go out and look under their respective node_modules folders and confirm that I can see your code changes from [jspm/npm@4aa9f8f](https://github.com/jspm/npm/commit/4aa9f8f9991189b8be2aa2e7e366109cc9808b0c) but when I run the app, I still get what appears to be the same errors.

![capture2](https://cloud.githubusercontent.com/assets/821554/7947419/a8f573e8-0942-11e5-84b1-144beff1cd4e.PNG)

**Comment by guybedford** [comment]
@32graham right, try running `jspm install npm:elasticsearch -f` here to manually override the cache. This is necessary when altering the endpoint version manually like this.

**Comment by 32graham** [comment]
Same errors still. Here is what I have done:

    jspm cc
    jspm install
    jspm install npm:elasticsearch -f -o override.json

**Comment by guybedford** [comment]
@32graham you need to ensure that the version of jspm-npm within jspm-cli is the master version, that is you need to run `npm install jspm/npm#master` from within jspm's project folder itself to make the link work correctly, so that jspm has npm on master in its own node_modules folder.

**Comment by 32graham** [comment]
Still getting the same errors.

What I have done:

    cd C:\Users\jgraham\Application Data\npm\node_modules\jspm
    npm install jspm/npm#master

Then I look in `C:\Users\jgraham\Application Data\npm\node_modules\jspm\jspm-npm\lib\node-conversion.js` and I see your recent changes so I am pretty sure that I am getting the latest code from the `master` branch.

Then, I go make sure that there is no jspm or jspm-npm in my project's local node_modules folder.

Then I run:

    jspm cc
    jspm install
    jspm install npm:elasticsearch -f -o override.json

But the problem with "Node tls module not supported in browsers" persists.

**Comment by guybedford** [comment]
@32graham thanks it turns out that this is a windows bug with the override itself despite it working for me on Mac. I'm looking into it.

**Comment by guybedford** [comment]
Continuing to track this at https://github.com/jspm/npm/issues/79.
